/* RESOLVENDO INCONSISTÊNCIAS DA TABELA HISTORICOS_BANCO*/

SELECT * FROM HISTORICOS_BANCO;

-- Verificando se há algum dado nulo na coluna CB_ID
SELECT * FROM HISTORICOS_BANCO
WHERE CB_ID IS NULL;

-- Alterando a coluna CB_ID para NOT NULL
ALTER TABLE HISTORICOS_BANCO
MODIFY CB_ID VARCHAR(16) NOT NULL;

-- Adicionando a PRIMARY KEY (chave primária)
ALTER TABLE HISTORICOS_BANCO
ADD PRIMARY KEY(CB_ID);

-- Para manter o padrão. Irei alterar os campos da coluna CB_PERSON_DEFAULT_ON_FILE
-- Sendo: N=0 e Y=1 
SELECT CB_PERSON_DEFAULT_ON_FILE FROM HISTORICOS_BANCO
GROUP BY CB_PERSON_DEFAULT_ON_FILE;

UPDATE HISTORICOS_BANCO SET CB_PERSON_DEFAULT_ON_FILE='0' 
WHERE CB_PERSON_DEFAULT_ON_FILE='N';

UPDATE HISTORICOS_BANCO SET CB_PERSON_DEFAULT_ON_FILE='1' 
WHERE CB_PERSON_DEFAULT_ON_FILE='Y';

UPDATE HISTORICOS_BANCO SET CB_PERSON_DEFAULT_ON_FILE=NULL
WHERE CB_PERSON_DEFAULT_ON_FILE='';

ALTER TABLE HISTORICOS_BANCO
MODIFY CB_PERSON_DEFAULT_ON_FILE INT;

-- Traduzindo o nome das colunas
ALTER TABLE HISTORICOS_BANCO
CHANGE CB_ID ID_HISTORICO VARCHAR(16);

ALTER TABLE HISTORICOS_BANCO
CHANGE CB_PERSON_DEFAULT_ON_FILE HISTORICO_INADIMPLENTE INT;

ALTER TABLE HISTORICOS_BANCO
CHANGE CB_PERSON_CRED_HIST_LENGTH ANOS_CARTAO_CREDITO INT;