/* RESOLVENDO INCONSISTÊNCIAS DA TABELA ID */

SELECT * FROM ID;

-- Verificando se há algum campo null
SELECT * FROM ID
WHERE PERSON_ID IS NULL OR LOAN_ID IS NULL OR CB_ID IS NULL;

-- Esta é uma tabela de relacionamento
-- Então será necessário referenciar as chaves primárias (PRIMARY KEY) como chaves estrangeiras (FOREIGN KEY)

-- Inicialmente já vemos que o tipo está errado
-- passando de TEXTO para VARCHAR(16)
ALTER TABLE ID
CHANGE PERSON_ID ID_SOLICITANTE VARCHAR(16) NOT NULL;

ALTER TABLE ID
CHANGE LOAN_ID ID_EMPRESTIMO VARCHAR(16) NOT NULL;

ALTER TABLE ID
CHANGE CB_ID ID_HISTORICO VARCHAR(16) NOT NULL;

-- Adicionando a chave estrangeira as colunas

ALTER TABLE ID ADD CONSTRAINT ID_SOLICITANTE
FOREIGN KEY(ID_SOLICITANTE) REFERENCES DADOS_MUTUARIOS(ID_SOLICITANTE);

ALTER TABLE ID ADD CONSTRAINT ID_EMPRESTIMO
FOREIGN KEY(ID_EMPRESTIMO) REFERENCES EMPRESTIMOS(ID_EMPRESTIMO);

ALTER TABLE ID ADD CONSTRAINT ID_HISTORICO
FOREIGN KEY(ID_HISTORICO) REFERENCES HISTORICOS_BANCO(ID_HISTORICO);